/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as ContinentsSlugRouteImport } from './routes/continents.$slug'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinentsSlugRoute = ContinentsSlugRouteImport.update({
  id: '/continents/$slug',
  path: '/continents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/continents/$slug': typeof ContinentsSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/continents/$slug': typeof ContinentsSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/countries': typeof CountriesIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/continents/$slug': typeof ContinentsSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/explore'
    | '/continents/$slug'
    | '/countries/$slug'
    | '/guides/$slug'
    | '/countries/'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/explore'
    | '/continents/$slug'
    | '/countries/$slug'
    | '/guides/$slug'
    | '/countries'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/explore'
    | '/continents/$slug'
    | '/countries/$slug'
    | '/guides/$slug'
    | '/countries/'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ExploreRoute: typeof ExploreRoute
  ContinentsSlugRoute: typeof ContinentsSlugRoute
  CountriesSlugRoute: typeof CountriesSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continents/$slug': {
      id: '/continents/$slug'
      path: '/continents/$slug'
      fullPath: '/continents/$slug'
      preLoaderRoute: typeof ContinentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ExploreRoute: ExploreRoute,
  ContinentsSlugRoute: ContinentsSlugRoute,
  CountriesSlugRoute: CountriesSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
